travis:
  secure:
    BINSTAR_TOKEN: WNkV9XfuYuBgH5btXajGqCF/iAcF5o2BrhhlSPisDQVNxEoHk3lzQOvdq7qrdt750G8dsIOeiAkgEe574FztelONUIWs0FYyjkppAGK3Kz9W7fIseUD3HcfArO69EC+lmmyHvOAqzNNutT+tIDeXUFFVViXDkgCqyKlCviebWP5fyRzUJIAZ4PfFIDabtCNnR2/Vm1aDFSuriy+61s6EeED9sWJZwbD26BLMb6wD84XtiAd6xzihIMbT5Tm/eGQzwB1IjAxspruV5hBQ7lrpF5gsyuCT3yobuPIS4uKeyVl2rQE2u+6iEudAT/PulWkRtj7YS6MPLCUO6fc0KRfGbuwxE+i4pq3h6vfw3oAPtGOzk021VjrDCBNFLMKtFnvrADcuo18XcMscAunxvOmWTj3UniyZnKkLWSp/NWu0YnLKBiWwlM0JB5/pIyJnwO6bbXS239sPa/vwFOqpgXx0UmLovi1gg++C+/Pb/uuyY//adFO/CWE5v8zmkMqCDq9rKQczjRWs6+iqT3mdndvxKWf3kGSYB7T0m7H8pZx/9ScloE/T5H3Rb1F2CWOZEwcsP2/gH+pe1UEgea6vO4iRSdXjPm8ST6SknRWaDgXcEJpP1q0ELmNR4Hl46CVvykLQBwHbcO0eM49+kxdSh/SR5KyyS8BGK9ppUBsn9iEHTSU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
