travis:
  secure:
    BINSTAR_TOKEN: uMlMJS//cvpq6xS5AwR3aAU5JpR/dDtgNFdXG1YEwWLvSaJyLpZQVniGJQGUtTC0hG3BKVOG+egVSwlQob9q/DvMFrXBgP5nvFk5XrfyHN5OigvINg6z2GtsjgISZxyXTJFpUNRAjdB3nRip5ztuO0fbFEEkytM2bZkUf8TH6i5zuUo/K8GFvMGE8GHFbcVCn4QcB5DMnHV+ghROCkM5glYFGbtbMszhT6ifKZs0lOMjhzBmmV/rCucLWP0gGeRYuoqPVECtsp1+ckpIrt/tBEiq6P1oW9P5PbwFinOEQ5QonHYXfW7Qj1ehi2e4gm8wKNRcw+jrQIAVbhS7W5i/iBoZFtRQIPxiaS2c3lIpQFWNs493bpZ9KgQtxtp/3C5RjD7O5DJHSIHr0TBcHF5cA9yMs2v/AC+KofC3MuwbKQs6RhR4ColwFUkC25yrrMWdyIGZKRNYZYUpEAyTPAfz91FVP8bQipcO+yH+wpdvyJ8JJrLP0JC5wXS4hj+tT1mK7SjRzWNrL3LpSbcjmVGL4BS+RBRvysDUeX/erjSJMrxEWWz0Lc3rjxetyL6ugj0Q8ahptdVtk+s2qnMEQI5DbjoHc3rbSJg823Sz66VS3Ko1zMDEEu6S6xLSNNeJH4LTSgYpxwVEBRej9dhlGbUkGRCJNqKlo4gf7BlDsSFZzYk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
